### PR TITLE
[+] Installation - Auto-register the service provider on Laravel 5.5+

### PR DESCRIPTION
**Pull request by m1guelpf**
This will make the package work with [auto-discovery](https://github.com/laravel/framework/pull/19420) in Laravel 5.5

### CODE REVIEW

**Comment by m1guelpf** [comment]
ping @arnaudbesnier

**Comment by m1guelpf** [comment]
@arnaudbesnier When Laravel users install this, they have to register the service provider as stated in the readme. With this change, Laravel 5.5+ users no longer have to do that, and can get up-and-running only by running composer install!

**Comment by arnaudbesnier** [comment]
So nice to get rid of this crappy way to add a package!
So we need to update the Readme too.

**Comment by m1guelpf** [comment]
@arnaudbesnier Done!

**Comment by arnaudbesnier** [comment]
Can you?

- [] Update the README.md (remove the unecessary setup step)
- [] Add a "Change" line in the CHANGELOG.md

Once done, I'll test and validate the PR before the end of the week.

Thank for the contribution 🌲🌲🌲

**Comment by m1guelpf** [comment]
@arnaudbesnier I've done the first. I am keeping the line because Laravel 5.4 and below still need this step.

**Comment by m1guelpf** [comment]
@arnaudbesnier Done!

**Comment by arnaudbesnier** [comment]
That's perfect, I'll test an onboarding with Laravel 5.5 to check if everything is fine!

**Pull request merged**
